name: Build and Deploy Vue.js Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Construire le projet Vue
      - name: Build project
        run: |
          npm run build
          echo "✅ Build terminé"

      # 5️⃣ Vérifier que le dossier dist/ existe
      - name: Verify dist folder
        run: |
          if [ ! -d "./dist" ]; then
            echo "❌ Dossier dist/ non trouvé !"
            exit 1
          fi
          echo "✅ dist/ trouvé, prêt pour le déploiement"
          ls -la ./dist

      # 6️⃣ Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
          keep_files: false
