name: Build and Deploy Vue.js Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # ✅ Permissions nécessaires pour GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1️⃣ Récupérer le repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js compatible Vite
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build du projet
      - name: Build project
        run: npm run build

      # 5️⃣ Upload des artefacts
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
