name: Build and Deploy Vue.js Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js compatible Vite
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Node >=22 recommandé pour Vite

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build du projet
      - name: Build project
        run: npm run build

      # 5️⃣ Déployer sur GitHub Pages
- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    # URL avec token pour push
    publish_dir: ./dist
    publish_branch: gh-pages
    user_name: 'github-actions[bot]'
    user_email: 'github-actions[bot]@users.noreply.github.com'
    # Authentification explicite
    github_token: ${{ secrets.GITHUB_TOKEN }}